"""Create Fake Post to Test in It

Revision ID: 5c51e6fcbee9
Revises: dd63e78bd1a6
Create Date: 2021-11-30 22:42:30.960518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c51e6fcbee9'
down_revision = 'dd63e78bd1a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fake_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('postBody', sa.String(length=1400), nullable=True),
    sa.Column('authorName', sa.String(length=200), nullable=True),
    sa.Column('imageField', sa.String(length=1400), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fake_post')
    # ### end Alembic commands ###
