"""Edit

Revision ID: aedc59049c03
Revises: 5c51e6fcbee9
Create Date: 2021-12-01 11:49:59.219703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aedc59049c03'
down_revision = '5c51e6fcbee9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fake_post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fake_post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('postBody', sa.VARCHAR(length=1400), nullable=True),
    sa.Column('authorName', sa.VARCHAR(length=200), nullable=True),
    sa.Column('imageField', sa.VARCHAR(length=1400), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
