"""users table

Revision ID: dd63e78bd1a6
Revises: 
Create Date: 2021-11-29 13:39:04.481772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd63e78bd1a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('postBody', sa.String(length=1400), nullable=True),
    sa.Column('authorName', sa.String(length=200), nullable=True),
    sa.Column('imageField', sa.String(length=1400), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###
